### ISSUE TITLE
Get a default color for the hand.

### ISSUE THREAD

**Issue by aaaustin10** [aaaustin10/csc545-project#1]
You will need to ask the user to place their hand in a predetermined place on the screen then take the average color at that location. It will be useful to have a starting point for which color to match.

**Comment by johnnyRose** [comment]
Looks at center two thirds of screen at first. User must keep their hand in the center until a confirmation message is printed to the console.

**Comment by aaaustin10** [comment]
Whoops, my track pad clicked that without my intention being to do so.
