### ISSUE TITLE
Add a blob description object

### ISSUE THREAD

**Issue by aaaustin10** [aaaustin10/csc545-project#3]
It should be beneficial to have an object the contains a description of the blob that we are tracking.

**Comment by johnnyRose** [comment]
Looks like this should be closed, but I'm not sure I completely understand it. Can you elaborate?

**Comment by aaaustin10** [comment]
You are correct. It should be closed.

**Comment by ClaudeWu** [comment]
what just closed?

**Comment by johnnyRose** [comment]
Are you reading and responding to these notifications on your email? You can get the full context by viewing these notifications directly on GitHub.

**Comment by ClaudeWu** [comment]
ye I did, but I just don't understand what "closed" mean right here... you
guys are talking about the description of the blob right...
