### ISSUE TITLE
Implement mouse click control through gestures

### ISSUE THREAD

**Issue by johnnyRose** [aaaustin10/csc545-project#4]
Please implement mouse click control through a gesture, similar to what was added to the attempt-at-click-detection branch. The object's current size should be compared to an average of the size of the object over the last n frames. If the percent change between the current size and the previous size is greater than some threshold, it should click or release the mouse button as required.

A boolean `isPressed` might come in handy here to prevent the mouse from trying to click while the button is already held (for dragging and dropping). 

Please commit changes to the gesture_detection file in the master branch. You will need to use the robot class - an example follows.

`import java.awt.event.*;`

`Robot robot`;

`try {
      robot = new Robot();
    } 
    catch (AWTException e) {
      println("Robot class not supported.");
      exit();
    }
`

`... (the rest of your code)...`

`robot.mousePress(InputEvent.BUTTON1_MASK); // mouse click`
`robot.mouseRelease(InputEvent.BUTTON1_MASK); // mouse release`

**Comment by ClaudeWu** [comment]
not clear understand about this, @aaaustin10 could you deal with it?
